workflows:
  ios-build:
    name: iOS Build
    platform: ios
    max_build_duration: 120
    environment:
      flutter: stable
    scripts:
      - flutter clean
      - flutter pub get
      - flutter build ios --release --no-codesign
    artifacts:
      - build/ios/iphoneos/*.ipa
    cache:
      paths:
        - build/