platform :ios, '12.0'  # Uncomment this line to specify the platform version

target 'Runner' do
  use_frameworks!  # Use dynamic frameworks

  # Add your actual app dependencies here
  # pod 'SomeDependency'
  
  target 'RunnerTests' do
    inherit! :search_paths
    # Add testing dependencies here if you need
  end
end