# Podfile
platform :ios, '12.0'

# Flutter config imports - add this part
flutter_application_path = File.dirname(File.realpath(__FILE__))
require File.expand_path(File.join('packages', 'flutter_tools', 'bin', 'podhelper'), flutter_application_path)

target 'Runner' do
  use_frameworks!
  
  # Flutter pods - this will now work
  install_all_flutter_pods(flutter_application_path)
  
  # Your Firebase pods
  pod 'Firebase/Core'
  pod 'Firebase/Messaging'
  
  target 'RunnerTests' do
    inherit! :search_paths
  end
end

# Ensure deployment target consistency
post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '12.0'
    end
  end
end